### PR TITLE
Release 0.7.6

### PR DESCRIPTION
**Pull request by freider**
Changes: 
* Fixes issues with wrapped generic base class inheritance

### CODE REVIEW

**Comment by freider** [comment]
@prbot approve

**Comment by freider** [comment]
@prbot approve

**Comment by mwaskom** [comment]
can confirm that 5 + 1 = 6; lgtm

**Comment by freider** [comment]
Thanks for the thorough review! 🙏

**Comment by mwaskom** [comment]
have to admit i leaned on the assistance of AI a little bit

**Pull request merged**
